/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro1041_qltc;

import KetNoiNhanh.Faster;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FormQLCT extends javax.swing.JInternalFrame {

    String colname[] = {"Mã giao dịch", "Tên giao dịch", "Số tiền", "Việc chi tiêu", "Hũ", "Ngày", "Ghi chú"};
    DefaultTableModel tableModel = new DefaultTableModel(colname, 0);
    Connection con;

    /**
     * Creates new form FormQLCT
     */
    String nguoidung;
    int id;

    public FormQLCT(String nguoidung,Connection con) {
        initComponents();
        this.nguoidung = nguoidung;
        this.con = con;
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối!");
        }
        LoadDataToCboHu();
        LoadDataToCboViecChiTieu();
        fillToTable();
    }

    public void LoadDataToCboHu() {
        try {
            String sql = "SELECT * FROM LUCHU ";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                cboHu.addItem(rs.getString("tenhu"));
            }
            cboHu.removeItem("Tat ca");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi load to combo hũ!");
        }
    }
    
    public void chonHu(String tenHu){
        cboHu.setSelectedItem(tenHu);
    }

    public void LoadDataToCboViecChiTieu() {
        try {
            String sql = "SELECT * FROM NGUONTIEN where loai='chi'";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                cboViecChiTieu.addItem(rs.getString("tennguon"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi load to combo : " + e);
        }
    }

    public boolean checkNull() {
        if (txtTenGiaoDich.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống tên giao dịch!");
            return false;
        } else if (txtSoTien.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống số tiền!");
            return false;
//        } else if (!txtSoTien.getText().matches("\\d")) {
//            JOptionPane.showMessageDialog(this, "Tiền chỉ được nhập số!");
//            return false;
        } else if (txtNgay.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không để trống ngày!");
            return false;
        } else {
            return true;
        }
    }

    public void fillToTable() {
        try {
            tableModel.setRowCount(0);
            String sql = "select * from THUCHI join NGUONTIEN on THUCHI.tennguon = NGUONTIEN.tennguon where loai = 'chi'";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("ten"));
                v.add(rs.getString("sotien"));
                v.add(rs.getString("tennguon"));
                v.add(rs.getString("tenhu"));
                v.add(rs.getString("ngay"));
                v.add(rs.getString("ghichu"));
                tableModel.addRow(v);
            }
            tblHienThi.setModel(tableModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e);
        }
    }

    public void showDetail() {
        int a = tblHienThi.getSelectedRow();

        id = Integer.parseInt(tblHienThi.getValueAt(a, 0).toString());
        cboViecChiTieu.setSelectedItem(tblHienThi.getValueAt(a, 3));
        txtTenGiaoDich.setText(tblHienThi.getValueAt(a, 1).toString());
        txtSoTien.setText(tblHienThi.getValueAt(a, 2).toString());
        txtNgay.setText(tblHienThi.getValueAt(a, 5).toString());
        cboHu.setSelectedItem(tblHienThi.getValueAt(a, 4).toString());
        txtGhiChu.setText(tblHienThi.getValueAt(a, 6).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelThongTin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboViecChiTieu = new javax.swing.JComboBox<>();
        cboHu = new javax.swing.JComboBox<>();
        txtTenGiaoDich = new javax.swing.JTextField();
        txtSoTien = new javax.swing.JTextField();
        txtNgay = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();
        panelLuaChon = new javax.swing.JPanel();
        btnMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("QUẢN LÍ CHI TIÊU");

        jLabel2.setText("Việc chi tiêu");

        jLabel3.setText("Tên giao dịch");

        jLabel5.setText("Số tiền");

        jLabel6.setText("Ngày");

        jLabel7.setText("Hũ");

        jLabel8.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incons/Edit.png"))); // NOI18N
        jButton1.setText("Chỉnh sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThongTinLayout = new javax.swing.GroupLayout(panelThongTin);
        panelThongTin.setLayout(panelThongTinLayout);
        panelThongTinLayout.setHorizontalGroup(
            panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(63, 63, 63)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboViecChiTieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboHu, 0, 216, Short.MAX_VALUE)
                    .addComponent(txtTenGiaoDich)
                    .addComponent(txtSoTien)
                    .addComponent(txtNgay)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelThongTinLayout.setVerticalGroup(
            panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboViecChiTieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(cboHu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã giao dịch", "Tên giao dịch", "Số tiền", "Việc chi tiêu", "Hũ", "Ngày", "Ghi chú"
            }
        ));
        tblHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHienThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHienThi);

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incons/Refresh.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incons/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incons/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incons/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLuaChonLayout = new javax.swing.GroupLayout(panelLuaChon);
        panelLuaChon.setLayout(panelLuaChonLayout);
        panelLuaChonLayout.setHorizontalGroup(
            panelLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLuaChonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLuaChonLayout.setVerticalGroup(
            panelLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLuaChonLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(panelThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(panelLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(panelThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(panelLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (checkNull()) {
            try {
                SimpleDateFormat ngay = new SimpleDateFormat("MM/dd/yyyy");
                Date day = ngay.parse(txtNgay.getText());
                String sql = "Insert into THUCHI values (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, txtTenGiaoDich.getText());
                ps.setInt(2, Integer.parseInt(txtSoTien.getText()));
                ps.setString(3, txtNgay.getText());
                ps.setString(4, cboViecChiTieu.getSelectedItem().toString());
                ps.setString(5, txtGhiChu.getText());
                ps.setString(6, cboHu.getSelectedItem().toString());
                ps.setString(7, nguoidung);
                int m = ps.executeUpdate();
                if (m > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm dữ liệu thành công!");
                    fillToTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Không thêm được dữ liệu!");
                }
                fillToTable();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        cboViecChiTieu.setSelectedIndex(0);
        cboHu.setSelectedIndex(0);
        txtTenGiaoDich.setText("");
        txtSoTien.setText("");
        txtNgay.setText("");
        txtGhiChu.setText("");
    }//GEN-LAST:event_btnMoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //String tenNguonTieu = cboNguonChi.getSelectedItem().toString();
        FormNguonTien f = new FormNguonTien(con);
        DuAn1.me.jDesktopPane1.add(f);
        f.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (checkNull()) {
            try {
                String sql = "UPDATE THUCHI SET ten=?, sotien=?, ngay=?, tennguon=?, ghichu=?, tenhu=?, tennguoidung=? where id=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, txtTenGiaoDich.getText());
                ps.setInt(2, Integer.parseInt(txtSoTien.getText()));
                ps.setString(3, txtNgay.getText());
                ps.setString(4, cboViecChiTieu.getSelectedItem().toString());
                ps.setString(5, txtGhiChu.getText());
                ps.setString(6, cboHu.getSelectedItem().toString());
                ps.setString(7, nguoidung);
                ps.setInt(8, id);
                int m = ps.executeUpdate();
                if (m > 0) {
                    JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công!");
                    fillToTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Không sửa được dữ liệu!");
                }
                fillToTable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi sửa dữ liệu!");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHienThiMouseClicked
        this.showDetail();
    }//GEN-LAST:event_tblHienThiMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?");
            if (choice == JOptionPane.YES_OPTION && choice >= 0) {
                String sql = "Delete from THUCHI where id=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, id);
                int m = ps.executeUpdate();
                if (m > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công!");
                    fillToTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Không xóa được dữ liệu!");
                }
            }
            fillToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa dữ liệu!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboHu;
    private javax.swing.JComboBox<String> cboViecChiTieu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelLuaChon;
    private javax.swing.JPanel panelThongTin;
    private javax.swing.JTable tblHienThi;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtSoTien;
    private javax.swing.JTextField txtTenGiaoDich;
    // End of variables declaration//GEN-END:variables
}
